-- ************************************************************************************
-- SISTEMA DE GESTIÓN DE INVENTARIO - CARNICERÍA (MASTER SCRIPT V11 - MERGED)
-- DESCRIPCIÓN: Script unificado con triggers de cálculo automático, asignación de ID
--              y datos históricos de movimientos.
-- ************************************************************************************

SET SERVEROUTPUT ON;
SET DEFINE OFF;

/************************************************************************************
* 1. LIMPIEZA DE ENTORNO (Clean Slate)
************************************************************************************/
BEGIN
    FOR c IN (SELECT table_name FROM user_tables WHERE table_name IN 
             ('AUDITORIAS_INVENTARIO', 'ALERTAS_INVENTARIO', 'MOVIMIENTOS_INVENTARIO', 
              'DETALLE_ORDEN', 'ORDENES_COMPRA', 'PRODUCTOS_CARNE', 'EMPLEADOS', 
              'CATEGORIAS_CARNE', 'PROVEEDORES', 'SUPERMERCADOS')) 
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    
    BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE pkg_inventario_carnes'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TYPE productos_alerta_varray FORCE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    
    EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
    DBMS_OUTPUT.PUT_LINE('--- Entorno limpiado correctamente ---');
END;
/

/************************************************************************************
* 2. CREACIÓN DE OBJETOS DE BASE DE DATOS
************************************************************************************/

CREATE OR REPLACE TYPE productos_alerta_varray AS VARRAY(100) OF NUMBER;
/

CREATE TABLE supermercados (
    supermercado_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150) NOT NULL,
    direccion           VARCHAR2(200),
    telefono            VARCHAR2(20),
    correo_contacto     VARCHAR2(100),
    estado              CHAR(1) DEFAULT 'A' CHECK (estado IN ('A','I')),
    fecha_registro      DATE DEFAULT SYSDATE
);

CREATE TABLE proveedores (
    proveedor_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150) NOT NULL,
    rut                 VARCHAR2(20) UNIQUE NOT NULL,
    telefono            VARCHAR2(20),
    correo              VARCHAR2(100) UNIQUE NOT NULL,
    estado              CHAR(1) DEFAULT 'A',
    fecha_registro      DATE DEFAULT SYSDATE,
    supermercado_id     NUMBER(10) REFERENCES supermercados(supermercado_id)
);

CREATE TABLE categorias_carne (
    categoria_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(100) NOT NULL,
    descripcion         VARCHAR2(200),
    estado              CHAR(1) DEFAULT 'A',
    supermercado_id     NUMBER(10) REFERENCES supermercados(supermercado_id)
);

CREATE TABLE empleados (
    empleado_id         NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150) NOT NULL,
    rut                 VARCHAR2(20) UNIQUE NOT NULL,
    cargo               VARCHAR2(100),
    telefono            VARCHAR2(20),
    correo              VARCHAR2(100),
    supermercado_id     NUMBER(10) REFERENCES supermercados(supermercado_id),
    estado              CHAR(1) DEFAULT 'A'
);

CREATE TABLE productos_carne (
    producto_id         NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150) NOT NULL,
    categoria_id        NUMBER(10) REFERENCES categorias_carne(categoria_id),
    precio_por_kg       NUMBER(10,2) CHECK (precio_por_kg > 0),
    stock_actual_kg     NUMBER(10,3) DEFAULT 0 CHECK (stock_actual_kg >= 0),
    stock_minimo_kg     NUMBER(10,3) DEFAULT 10 CHECK (stock_minimo_kg >= 0),
    proveedor_id        NUMBER(10) REFERENCES proveedores(proveedor_id),
    supermercado_id     NUMBER(10) REFERENCES supermercados(supermercado_id),
    estado              CHAR(1) DEFAULT 'A'
);

CREATE TABLE ordenes_compra (
    orden_id            NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    proveedor_id        NUMBER(10) REFERENCES proveedores(proveedor_id),
    supermercado_id     NUMBER(10) REFERENCES supermercados(supermercado_id),
    fecha_orden         DATE DEFAULT SYSDATE,
    total               NUMBER(12,2),
    estado              VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'RECIBIDA', 'CANCELADA'))
);

CREATE TABLE detalle_orden (
    detalle_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    orden_id            NUMBER(10) REFERENCES ordenes_compra(orden_id),
    producto_id         NUMBER(10) REFERENCES productos_carne(producto_id),
    cantidad_kg         NUMBER(10,3) CHECK (cantidad_kg > 0),
    precio_por_kg       NUMBER(10,2) CHECK (precio_por_kg >= 0)
);

CREATE TABLE movimientos_inventario (
    movimiento_id       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    producto_id         NUMBER(10) REFERENCES productos_carne(producto_id),
    tipo_movimiento     VARCHAR2(20) CHECK (tipo_movimiento IN ('INGRESO','EGRESO', 'MERMA')),
    cantidad_kg         NUMBER(10,3) CHECK (cantidad_kg > 0),
    fecha_movimiento    DATE DEFAULT SYSDATE,
    observacion         VARCHAR2(200),
    empleado_id         NUMBER(10) REFERENCES empleados(empleado_id),
    supermercado_id     NUMBER(10) REFERENCES supermercados(supermercado_id)
);

CREATE TABLE alertas_inventario (
    alerta_id           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    producto_id         NUMBER(10) REFERENCES productos_carne(producto_id),
    fecha_alerta        DATE DEFAULT SYSDATE,
    tipo_alerta         VARCHAR2(50) CHECK (tipo_alerta IN ('BAJO STOCK','SIN STOCK', 'POR_VENCER')),
    descripcion         VARCHAR2(200) NOT NULL,
    atendida            CHAR(1) DEFAULT 'N' CHECK (atendida IN ('S','N'))
);

CREATE TABLE auditorias_inventario (
    auditoria_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    producto_id         NUMBER(10) REFERENCES productos_carne(producto_id),
    fecha_hora          TIMESTAMP DEFAULT SYSTIMESTAMP,
    empleado_id         NUMBER(10) REFERENCES empleados(empleado_id),
    supermercado_id     NUMBER(10) REFERENCES supermercados(supermercado_id),
    stock_sistema_kg    NUMBER(10,3),
    stock_real_kg       NUMBER(10,3),
    diferencia_kg       NUMBER(10,3),
    motivo              VARCHAR2(200)
);

-- Índices
CREATE INDEX idx_prod_cat_super ON productos_carne(categoria_id, supermercado_id);
CREATE INDEX idx_oc_prov ON ordenes_compra(proveedor_id);
CREATE INDEX idx_mov_prod_fecha ON movimientos_inventario(producto_id, fecha_movimiento);
/

/************************************************************************************
* 2.1. FIX: REINICIO DE SECUENCIA ORDENES_COMPRA (Evita ORA-00001)
************************************************************************************/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ORDENES_COMPRA MODIFY PRIMARY KEY GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100)';
    EXECUTE IMMEDIATE 'ALTER TABLE DETALLE_ORDEN MODIFY PRIMARY KEY GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1000)';
    DBMS_OUTPUT.PUT_LINE('--- FIX: Secuencias iniciadas en 100/1000. ---');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

/************************************************************************************
* 3. TRIGGERS
************************************************************************************/

-- Trigger 3.1: Alertas de Stock
CREATE OR REPLACE TRIGGER trg_alerta_stock
AFTER UPDATE OF stock_actual_kg ON productos_carne
FOR EACH ROW
DECLARE
    v_tipo_alerta VARCHAR2(50);
    l_count NUMBER;
BEGIN
    IF :NEW.stock_actual_kg <= NVL(:NEW.stock_minimo_kg, 0) AND :OLD.stock_actual_kg > NVL(:NEW.stock_minimo_kg, 0) THEN
        v_tipo_alerta := CASE WHEN :NEW.stock_actual_kg = 0 THEN 'SIN STOCK' ELSE 'BAJO STOCK' END;
        SELECT COUNT(*) INTO l_count FROM alertas_inventario WHERE producto_id = :NEW.producto_id AND tipo_alerta = v_tipo_alerta AND atendida = 'N';
        IF l_count = 0 THEN
           INSERT INTO alertas_inventario (producto_id, tipo_alerta, descripcion) VALUES (:NEW.producto_id, v_tipo_alerta, 'El corte "' || :NEW.nombre || '" requiere reposición.');
        END IF;
    END IF;
END;
/

-- Trigger 3.2: Cálculo Automático de Total Orden (Nuevo)
CREATE OR REPLACE TRIGGER trg_calc_total_orden
AFTER INSERT OR UPDATE OR DELETE ON detalle_orden
FOR EACH ROW
BEGIN
    -- CASO 1: Insertando una fila nueva
    IF INSERTING THEN
        UPDATE ordenes_compra
        SET total = NVL(total, 0) + (:NEW.cantidad_kg * :NEW.precio_por_kg)
        WHERE orden_id = :NEW.orden_id;

    -- CASO 2: Borrando una fila
    ELSIF DELETING THEN
        UPDATE ordenes_compra
        SET total = NVL(total, 0) - (:OLD.cantidad_kg * :OLD.precio_por_kg)
        WHERE orden_id = :OLD.orden_id;

    -- CASO 3: Modificando una fila existente
    ELSIF UPDATING THEN
        UPDATE ordenes_compra
        SET total = NVL(total, 0) 
                    - (:OLD.cantidad_kg * :OLD.precio_por_kg) -- Restamos lo viejo
                    + (:NEW.cantidad_kg * :NEW.precio_por_kg) -- Sumamos lo nuevo
        WHERE orden_id = :NEW.orden_id;
    END IF;
END;
/

-- Trigger 3.3: Asignar Orden ID desde APEX (Nuevo)
CREATE OR REPLACE TRIGGER trg_asignar_orden_detalle
BEFORE INSERT ON detalle_orden
FOR EACH ROW
BEGIN
    -- Si el producto viene sin ID de Orden (porque es nueva),
    -- le asignamos el ID que está actualmente en la pantalla (P13_ORDEN_ID)
    IF :NEW.orden_id IS NULL THEN
        :NEW.orden_id := v('P13_ORDEN_ID');
    END IF;
END;
/

/************************************************************************************
* 4. PAQUETE PL/SQL
************************************************************************************/
CREATE OR REPLACE PACKAGE pkg_inventario_carnes AS
    MAX_DELTA_KG         CONSTANT NUMBER := 1000;
    DEFAULT_STOCK_MINIMO CONSTANT NUMBER := 10;
    ex_stock_insuficiente        EXCEPTION; PRAGMA EXCEPTION_INIT(ex_stock_insuficiente, -20010);
    ex_cantidad_invalida         EXCEPTION; PRAGMA EXCEPTION_INIT(ex_cantidad_invalida, -20011);
    ex_tipo_movimiento_invalido EXCEPTION; PRAGMA EXCEPTION_INIT(ex_tipo_movimiento_invalido, -20012);
    ex_producto_no_encontrado   EXCEPTION; PRAGMA EXCEPTION_INIT(ex_producto_no_encontrado, -20013);
    ex_orden_no_encontrada       EXCEPTION; PRAGMA EXCEPTION_INIT(ex_orden_no_encontrada, -20022);
    ex_orden_ya_recibida         EXCEPTION; PRAGMA EXCEPTION_INIT(ex_orden_ya_recibida, -20024);
    ex_orden_cancelada           EXCEPTION; PRAGMA EXCEPTION_INIT(ex_orden_cancelada, -20025);

    PROCEDURE registrar_movimiento(p_producto_id IN NUMBER, p_tipo_movimiento IN VARCHAR2, p_cantidad_kg IN NUMBER, p_empleado_id IN NUMBER, p_supermercado_id IN NUMBER);
    FUNCTION verificar_stock_kg(p_producto_id IN NUMBER) RETURN NUMBER;
    PROCEDURE crear_orden_compra_header(p_proveedor_id IN NUMBER, p_supermercado_id IN NUMBER, p_nueva_orden_id OUT NUMBER);
    PROCEDURE agregar_detalle_orden(p_orden_id IN NUMBER, p_producto_id IN NUMBER, p_cantidad_kg IN NUMBER, p_precio_por_kg IN NUMBER);
    PROCEDURE recibir_orden_compra(p_orden_id IN NUMBER, p_empleado_id IN NUMBER);
    FUNCTION obtener_productos_bajo_minimo(p_categoria_id IN NUMBER) RETURN productos_alerta_varray;
    PROCEDURE registrar_auditoria_conteo (p_producto_id IN NUMBER, p_cantidad_real_kg IN NUMBER, p_empleado_id IN NUMBER, p_supermercado_id IN NUMBER, p_motivo IN VARCHAR2 DEFAULT 'CONTEO FISICO');
END pkg_inventario_carnes;
/

CREATE OR REPLACE PACKAGE BODY pkg_inventario_carnes AS
    PROCEDURE p_actualizar_stock(p_producto_id IN NUMBER, p_delta_kg IN NUMBER) IS
    BEGIN UPDATE productos_carne SET stock_actual_kg = stock_actual_kg + p_delta_kg WHERE producto_id = p_producto_id; END p_actualizar_stock;

    PROCEDURE registrar_movimiento(p_producto_id IN NUMBER, p_tipo_movimiento IN VARCHAR2, p_cantidad_kg IN NUMBER, p_empleado_id IN NUMBER, p_supermercado_id IN NUMBER) IS
        v_stock_actual_kg NUMBER;
        v_sign NUMBER;
        v_movimiento_norm VARCHAR2(20) := UPPER(TRIM(p_tipo_movimiento));
    BEGIN
        IF p_cantidad_kg <= 0 OR p_cantidad_kg > MAX_DELTA_KG THEN RAISE ex_cantidad_invalida; END IF;
        SELECT stock_actual_kg INTO v_stock_actual_kg FROM productos_carne WHERE producto_id = p_producto_id FOR UPDATE;
        IF v_movimiento_norm IN ('EGRESO', 'MERMA') THEN
            IF v_stock_actual_kg < p_cantidad_kg THEN RAISE ex_stock_insuficiente; END IF;
            v_sign := -1;
        ELSIF v_movimiento_norm = 'INGRESO' THEN v_sign := 1;
        ELSE RAISE ex_tipo_movimiento_invalido; END IF;
        INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad_kg, empleado_id, supermercado_id)
        VALUES (p_producto_id, v_movimiento_norm, p_cantidad_kg, p_empleado_id, p_supermercado_id);
        p_actualizar_stock(p_producto_id, v_sign * p_cantidad_kg);
    EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20013, 'Producto no encontrado: ' || p_producto_id);
    END registrar_movimiento;

    FUNCTION verificar_stock_kg(p_producto_id IN NUMBER) RETURN NUMBER IS
        v_stock_kg NUMBER;
    BEGIN SELECT stock_actual_kg INTO v_stock_kg FROM productos_carne WHERE producto_id = p_producto_id; RETURN v_stock_kg;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END verificar_stock_kg;

    PROCEDURE crear_orden_compra_header(p_proveedor_id IN NUMBER, p_supermercado_id IN NUMBER, p_nueva_orden_id OUT NUMBER) IS
    BEGIN INSERT INTO ordenes_compra (proveedor_id, supermercado_id, total) VALUES (p_proveedor_id, p_supermercado_id, 0) RETURNING orden_id INTO p_nueva_orden_id;
    EXCEPTION WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20020, 'Error crear orden: ' || SQLERRM); END crear_orden_compra_header;

    PROCEDURE agregar_detalle_orden(p_orden_id IN NUMBER, p_producto_id IN NUMBER, p_cantidad_kg IN NUMBER, p_precio_por_kg IN NUMBER) IS
    BEGIN
        INSERT INTO detalle_orden (orden_id, producto_id, cantidad_kg, precio_por_kg) VALUES (p_orden_id, p_producto_id, p_cantidad_kg, p_precio_por_kg);
        UPDATE ordenes_compra SET total = NVL(total, 0) + (p_cantidad_kg * p_precio_por_kg) WHERE orden_id = p_orden_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20021, 'Datos no existen.'); WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20020, 'Error detalle: ' || SQLERRM);
    END agregar_detalle_orden;

    PROCEDURE recibir_orden_compra(p_orden_id IN NUMBER, p_empleado_id IN NUMBER) IS
        CURSOR c_detalle IS SELECT producto_id, cantidad_kg FROM detalle_orden WHERE orden_id = p_orden_id;
        v_supermercado_id NUMBER; v_orden_estado VARCHAR2(20);
    BEGIN
        SELECT estado, supermercado_id INTO v_orden_estado, v_supermercado_id FROM ordenes_compra WHERE orden_id = p_orden_id FOR UPDATE;
        IF v_orden_estado = 'RECIBIDA' THEN RAISE ex_orden_ya_recibida; ELSIF v_orden_estado = 'CANCELADA' THEN RAISE ex_orden_cancelada; END IF;
        FOR v_row IN c_detalle LOOP registrar_movimiento(v_row.producto_id, 'INGRESO', v_row.cantidad_kg, p_empleado_id, v_supermercado_id); END LOOP;
        UPDATE ordenes_compra SET estado = 'RECIBIDA' WHERE orden_id = p_orden_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN RAISE ex_orden_no_encontrada; END recibir_orden_compra;

    FUNCTION obtener_productos_bajo_minimo (p_categoria_id IN NUMBER) RETURN productos_alerta_varray IS
        v_lista_ids productos_alerta_varray := productos_alerta_varray();
    BEGIN SELECT producto_id BULK COLLECT INTO v_lista_ids FROM productos_carne WHERE categoria_id = p_categoria_id AND stock_actual_kg < stock_minimo_kg; RETURN v_lista_ids;
    EXCEPTION WHEN OTHERS THEN RETURN productos_alerta_varray(); END obtener_productos_bajo_minimo;

    PROCEDURE registrar_auditoria_conteo (p_producto_id IN NUMBER, p_cantidad_real_kg IN NUMBER, p_empleado_id IN NUMBER, p_supermercado_id IN NUMBER, p_motivo IN VARCHAR2 DEFAULT 'CONTEO FISICO') IS
        v_stock_sistema_kg NUMBER; v_diferencia_kg NUMBER;
    BEGIN
        IF p_cantidad_real_kg < 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Cantidad negativa.'); END IF;
        BEGIN SELECT stock_actual_kg INTO v_stock_sistema_kg FROM productos_carne WHERE producto_id = p_producto_id FOR UPDATE;
        EXCEPTION WHEN NO_DATA_FOUND THEN RAISE ex_producto_no_encontrado; END;
        v_diferencia_kg := p_cantidad_real_kg - v_stock_sistema_kg;
        IF v_diferencia_kg != 0 THEN
            INSERT INTO auditorias_inventario (producto_id, fecha_hora, empleado_id, supermercado_id, stock_sistema_kg, stock_real_kg, diferencia_kg, motivo)
            VALUES (p_producto_id, SYSTIMESTAMP, p_empleado_id, p_supermercado_id, v_stock_sistema_kg, p_cantidad_real_kg, v_diferencia_kg, p_motivo);
            UPDATE productos_carne SET stock_actual_kg = p_cantidad_real_kg WHERE producto_id = p_producto_id;
        END IF;
    EXCEPTION WHEN OTHERS THEN RAISE; END registrar_auditoria_conteo;
END pkg_inventario_carnes;
/

/************************************************************************************
* 5. CARGA DE DATOS MAESTROS Y PRODUCTOS (CONSOLIDADO 1-33)
************************************************************************************/
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- 5. Consolidando todos los Maestros y Productos (1-33)... ---');

    -- Supermercados
    INSERT INTO supermercados (supermercado_id, nombre, direccion) VALUES (1, 'Supermercado Central', 'Av. Principal 123');
    INSERT INTO supermercados (supermercado_id, nombre, direccion) VALUES (2, 'Sucursal Norte', 'Calle Falsa 456');
    INSERT INTO supermercados (supermercado_id, nombre, direccion, estado) VALUES (3, 'Bodega Logística', 'Ruta 5 Sur Km 100', 'I');

    -- Categorías
    INSERT ALL
         INTO categorias_carne (categoria_id, nombre, supermercado_id) VALUES (1, 'Vacuno', 1)
         INTO categorias_carne (categoria_id, nombre, supermercado_id) VALUES (2, 'Pollo', 1)
         INTO categorias_carne (categoria_id, nombre, supermercado_id) VALUES (3, 'Cerdo', 1)
         INTO categorias_carne (categoria_id, nombre, supermercado_id) VALUES (4, 'Pavo', 2)
         INTO categorias_carne (categoria_id, nombre, supermercado_id) VALUES (5, 'Cordero', 1)
    SELECT 1 FROM DUAL;

    -- Empleados
    INSERT ALL
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (1, 'Juan Pérez', '1-1', 'Jefe de Carnicería', 1)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (2, 'Ana Rojas', '2-2', 'Carnicera', 1)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (3, 'Carlos Muñoz', '3-3', 'Bodeguero', 3)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (4, 'María López', '4-4', 'Carnicera', 2)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (5, 'Pedro Soto', '5-5', 'Jefe de Sección', 2)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (6, 'Luisa Vera', '6-6', 'Ayudante Carnicero', 1)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (7, 'Jorge Díaz', '7-7', 'Reponedor', 2)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id, estado) VALUES (8, 'Elena Gómez', '8-8', 'Ex-Carnicera', 1, 'I')
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (9, 'Roberto Gómez', '12.345.678-9', 'Bodeguero', 1) 
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (10, 'Sofía Vergara', '13.456.789-0', 'Carnicera', 2) 
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (11, 'Miguel Torres', '14.567.890-K', 'Jefe de Compras', 1)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (12, 'Andrés Rojas', '15.678.901-2', 'Cajero', 1)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (13, 'Elena Soto', '16.789.012-3', 'Reponedora', 2)
         INTO empleados (empleado_id, nombre, rut, cargo, supermercado_id) VALUES (14, 'Mario Diaz', '17.890.123-4', 'Supervisor', 1)
    SELECT 1 FROM DUAL;

    -- Proveedores
    INSERT ALL
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (1, 'Frigorífico del Sur', '77.123.456-K', 'ventas@frigosur.cl', 1)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (2, 'Carnes Premium Ltda.', '78.987.654-J', 'contacto@carnespremium.cl', 1)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (3, 'Distribuidora Andina', '76.543.210-9', 'pedidos@andina.com', 2)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (4, 'Aves del Campo', '75.111.222-3', 'aves@campo.cl', 1)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id, estado) VALUES (5, 'Proveedor Antiguo', '70.000.000-0', 'old@prov.com', 1, 'I')
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (6, 'Importadora El Ganadero', '88.222.333-1', 'contacto@ganadero.cl', 1)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (7, 'Avícola San Antonio', '99.111.444-2', 'ventas@sanantonio.cl', 2)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (8, 'Cerdo Austral', '55.666.777-8', 'pedidos@austral.cl', 1)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (9, 'La Crianza', '66.333.444-5', 'ventas@crianza.cl', 1)
         INTO proveedores (proveedor_id, nombre, rut, correo, supermercado_id) VALUES (10, 'Pollos de Ñuble', '71.555.666-7', 'contacto@nuble.cl', 2)
    SELECT 1 FROM DUAL;

    -- PRODUCTOS (1-33) - CON STOCK VARIADO INCLUIDO
    INSERT ALL
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (1, 'Lomo Vetado', 1, 19990, 45.500, 5.0, 1, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (2, 'Asiento Picana', 1, 15500, 32.000, 8.0, 2, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (3, 'Entraña', 1, 22500, 12.500, 3.0, 1, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (4, 'Posta Negra', 1, 11990, 50.000, 10.0, 2, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (5, 'Tapabarriga', 1, 13490, 25.000, 6.0, 1, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (6, 'Pechuga Entera', 2, 6990, 120.000, 10.0, 4, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (7, 'Trutro Corto', 2, 4500, 95.000, 5.0, 4, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (8, 'Alitas de Pollo', 2, 3990, 80.500, 12.0, 4, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (9, 'Pollo Entero Faenado', 2, 3500, 60.000, 8.0, 4, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (10, 'Pulpa Pierna', 3, 7200, 40.000, 7.5, 2, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (11, 'Costillar Ahumado', 3, 9900, 35.000, 4.0, 2, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (12, 'Pechuga Pavo', 4, 8990, 18.000, 5.0, 4, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (13, 'Filete Premium', 1, 24990, 15.000, 8.0, 2, 1) 
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (14, 'Huachalomo', 1, 8990, 55.000, 15.0, 1, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (15, 'Abastero', 1, 9500, 48.000, 12.0, 1, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (16, 'Chuleta Centro', 3, 6500, 50.000, 10.0, 2, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (17, 'Malaya de Cerdo', 3, 8500, 18.500, 5.0, 2, 1) 
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (18, 'Chuleta Cordero', 5, 18990, 8.000, 4.0, 2, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (19, 'Osobuco', 1, 5990, 30.000, 20.0, 1, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (20, 'Posta Rosada', 1, 10500, 42.000, 30.0, 2, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (21, 'Pechuga Fileteada', 2, 8500, 100.000, 40.0, 4, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (22, 'Lomo de Cerdo', 3, 7990, 28.000, 25.0, 2, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (23, 'Trutro Pavo', 4, 5200, 25.000, 15.0, 4, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (24, 'Choclillo', 1, 9800, 33.000, 15.0, 1, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (25, 'Ganso', 1, 10990, 22.000, 10.0, 2, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (26, 'Palanca', 1, 16990, 14.000, 8.0, 1, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (27, 'Pata de Pollo', 2, 2990, 50.000, 25.0, 4, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (28, 'Carne Molida Pollo', 2, 4990, 45.000, 15.0, 4, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (29, 'Pernil', 3, 5800, 0.000, 20.0, 2, 1) -- SIN STOCK (Caso Pruba)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (30, 'Costilla de Cerdo', 3, 8500, 25.000, 10.0, 2, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (31, 'Escalopa Pavo', 4, 9500, 15.000, 6.0, 4, 2)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (32, 'Pierna Cordero', 5, 17500, 10.000, 5.0, 2, 1)
         INTO productos_carne (producto_id, nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id) VALUES (33, 'Rack Cordero', 5, 25990, 2.500, 3.0, 2, 1) -- ALERTA INICIAL (Bajo Minimo)
    SELECT 1 FROM DUAL;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Datos maestros y 33 productos cargados exitosamente. FKs aseguradas.');
END;
/

/************************************************************************************
* 5.1. AJUSTE DE STOCK INICIAL (Para soportar Egreso de Pruebas/Volumen)
************************************************************************************/
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- 5.1. Ajustando stock inicial para tests/volumen ---');
    UPDATE productos_carne SET stock_actual_kg = 30.0 WHERE producto_id = 1; 
    UPDATE productos_carne SET stock_actual_kg = 50.0 WHERE producto_id = 13;
    UPDATE productos_carne SET stock_actual_kg = 30.0 WHERE producto_id = 19;
    COMMIT;
END;
/

/************************************************************************************
* 6. PRUEBAS UNITARIAS Y CARGA TRANSACCIONAL (Movimientos y Órdenes)
************************************************************************************/
DECLARE
    v_nueva_orden_id NUMBER;
    v_emp_venta_id CONSTANT NUMBER := 2; -- Ana Rojas (Carnicera)
    v_emp_compra_id CONSTANT NUMBER := 1; -- Juan Pérez (Jefe Carnicería)
    -- CORRECCIÓN: Variable renombrada a v_sup_central para coincidir con el uso
    v_sup_central CONSTANT NUMBER := 1; -- Supermercado Central (ID 1)
    v_sup_id_norte CONSTANT NUMBER := 2; -- Sucursal Norte (ID 2)
    
    v_prov_frigo CONSTANT NUMBER := 1;
    v_prov_premium CONSTANT NUMBER := 2;
    v_prov_distribuidora CONSTANT NUMBER := 3; -- Distribuidora Andina
    v_prov_aves CONSTANT NUMBER := 4;
    v_prov_antiguo CONSTANT NUMBER := 5;
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 6. Ejecutando Pruebas y Transacciones (Volumen) ---');
    
    -- 6.1: Movimientos Iniciales de Prueba
    pkg_inventario_carnes.registrar_movimiento(1, 'INGRESO', 20.5, 1, 1);
    pkg_inventario_carnes.registrar_movimiento(6, 'INGRESO', 35.0, 1, 1);
    pkg_inventario_carnes.registrar_movimiento(10, 'INGRESO', 15.8, 1, 1);
    pkg_inventario_carnes.registrar_movimiento(10, 'MERMA', 0.3, 2, 1);
    
    -- 6.2: Movimiento que activa alerta de bajo stock (Lomo)
    pkg_inventario_carnes.registrar_movimiento(1, 'EGRESO', 16.0, 2, 1); 
    
    -- 6.3: Ciclo de Compra de Prueba (Orden 100)
    pkg_inventario_carnes.crear_orden_compra_header(1, 1, v_nueva_orden_id); -- Orden ID = 100
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 6, 30.0, 6500);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 7, 25.0, 4000);
    pkg_inventario_carnes.recibir_orden_compra(v_nueva_orden_id, 1);
    
    -- 6.4: Simulación de Stock Crítico (Genera ALERTA)
    pkg_inventario_carnes.registrar_movimiento(13, 'EGRESO', 25.0, 2, 1); -- Filete Premium -> Bajo Stock
    pkg_inventario_carnes.registrar_movimiento(17, 'INGRESO', 5.0, 1, 1);
    pkg_inventario_carnes.registrar_movimiento(17, 'EGRESO', 5.0, 2, 1);    -- Malaya de Cerdo -> Sin Stock
    pkg_inventario_carnes.registrar_movimiento(1, 'EGRESO', 2.0, 2, 1);     -- Lomo -> Más Crítico

    -- 6.5: Generando 10 Órdenes de Compra Adicionales (Volumen)
    
    -- Orden 101: Reposición Masiva Vacuno (Recibida, Histórica)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_frigo, v_sup_central, v_nueva_orden_id);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 1, 100, 18500); 
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 13, 30, 22000); 
    pkg_inventario_carnes.recibir_orden_compra(v_nueva_orden_id, 1);
    UPDATE ordenes_compra SET fecha_orden = SYSDATE - 30 WHERE orden_id = v_nueva_orden_id;

    -- Orden 102: Pollo (Recibida, Histórica)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_aves, v_sup_central, v_nueva_orden_id);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 6, 200, 6200);  
    pkg_inventario_carnes.recibir_orden_compra(v_nueva_orden_id, 1);
    UPDATE ordenes_compra SET fecha_orden = SYSDATE - 20 WHERE orden_id = v_nueva_orden_id;

    -- Orden 103: Cortes Premium (Recibida, Histórica)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_premium, v_sup_central, v_nueva_orden_id);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 3, 50, 21000);
    pkg_inventario_carnes.recibir_orden_compra(v_nueva_orden_id, 1);
    UPDATE ordenes_compra SET fecha_orden = SYSDATE - 10 WHERE orden_id = v_nueva_orden_id;
    
    -- Orden 104: Pedido Grande de Cerdo (PENDIENTE)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_distribuidora, v_sup_central, v_nueva_orden_id); 
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 11, 80, 9200);
    
    -- Orden 105: Reposición Urgente Pavo (PENDIENTE)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_aves, v_sup_central, v_nueva_orden_id);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 12, 30, 8500); 
    
    -- Orden 106: Mix Parrillero (PENDIENTE)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_frigo, v_sup_central, v_nueva_orden_id);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 2, 45, 14900);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 24, 50, 9100);

    -- Orden 107: Pedido Sucursal Norte (PENDIENTE)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_premium, v_sup_id_norte, v_nueva_orden_id);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 4, 100, 11000); 

    -- Orden 108: Cancelada por precio
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_antiguo, v_sup_central, v_nueva_orden_id);
    UPDATE ordenes_compra SET estado = 'CANCELADA' WHERE orden_id = v_nueva_orden_id;

    -- Orden 109: Cancelada por error
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_aves, v_sup_central, v_nueva_orden_id);
    UPDATE ordenes_compra SET estado = 'CANCELADA' WHERE orden_id = v_nueva_orden_id;
    
    -- Orden 110: Cordero (Recibida Hoy)
    pkg_inventario_carnes.crear_orden_compra_header(v_prov_premium, v_sup_central, v_nueva_orden_id);
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 18, 20, 17000);
    pkg_inventario_carnes.recibir_orden_compra(v_nueva_orden_id, 1);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Transacciones y pruebas completadas. El inventario está listo.');
END;
/

/************************************************************************************
* 7. MOVIMIENTOS HISTÓRICOS ADICIONALES (NUEVO)
************************************************************************************/
BEGIN
    -- Movimientos de AYER (SYSDATE - 1)
    INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad_kg, fecha_movimiento, empleado_id, supermercado_id)
    VALUES (6, 'INGRESO', 120, SYSDATE - 1, 1, 1); -- Compramos Pollo ayer
    
    INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad_kg, fecha_movimiento, empleado_id, supermercado_id)
    VALUES (1, 'EGRESO', 45, SYSDATE - 1, 2, 1);    -- Vendimos Lomo ayer

    -- Movimientos de HACE 2 DÍAS (SYSDATE - 2)
    INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad_kg, fecha_movimiento, empleado_id, supermercado_id)
    VALUES (1, 'INGRESO', 80, SYSDATE - 2, 1, 1);  -- Repusimos Lomo
    
    INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad_kg, fecha_movimiento, empleado_id, supermercado_id)
    VALUES (6, 'EGRESO', 60, SYSDATE - 2, 2, 1);    -- Vendimos Pollo

    -- Movimientos de HACE 3 DÍAS (SYSDATE - 3)
    INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad_kg, fecha_movimiento, empleado_id, supermercado_id)
    VALUES (13, 'EGRESO', 30, SYSDATE - 3, 2, 1);  -- Venta normal
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('--- Movimientos históricos insertados correctamente ---');
END;
/


SET SERVEROUTPUT ON;

DECLARE
    v_nueva_orden_id NUMBER;
    
    -- Configuración de la compra
    v_proveedor_id    NUMBER := 1;  -- Ej: Frigorífico del Sur
    v_supermercado_id NUMBER := 1;  -- Ej: Supermercado Central
BEGIN
    -- 1. Crear la Cabecera (El ID se genera automáticamente y se guarda en v_nueva_orden_id)
    pkg_inventario_carnes.crear_orden_compra_header(
        p_proveedor_id    => v_proveedor_id,
        p_supermercado_id => v_supermercado_id,
        p_nueva_orden_id  => v_nueva_orden_id
    );

    -- 2. Agregar Detalles (Productos) a esa orden
    -- Parametros: Orden ID, Producto ID, Cantidad KG, Precio Costo
    
    -- Agregamos 50 KG de Lomo Vetado (ID 1)
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 5, 50, 18500);
    
    -- Agregamos 100 KG de Pechuga Entera (ID 6)
    pkg_inventario_carnes.agregar_detalle_orden(v_nueva_orden_id, 8, 100, 6200);

    -- 3. Confirmar transacción
    COMMIT;
    
    -- 4. Imprimir resultado
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('¡Orden creada exitosamente!');
    DBMS_OUTPUT.PUT_LINE('Número de Orden: ' || v_nueva_orden_id);
    DBMS_OUTPUT.PUT_LINE('Estado actual:   PENDIENTE');
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
END;
/
