/************************************************************************************
*
* SCRIPT DE LIMPIEZA
*
************************************************************************************/


DROP PACKAGE pkg_inventario_carnes;
DROP TRIGGER trg_alerta_stock;
DROP TYPE productos_alerta_varray; -- Borrar el tipo VARRAY también
DROP TABLE detalle_orden CASCADE CONSTRAINTS;
DROP TABLE ordenes_compra CASCADE CONSTRAINTS;
DROP TABLE auditorias_inventario CASCADE CONSTRAINTS;
DROP TABLE alertas_inventario CASCADE CONSTRAINTS;
DROP TABLE movimientos_inventario CASCADE CONSTRAINTS;
DROP TABLE productos_carne CASCADE CONSTRAINTS;
DROP TABLE empleados CASCADE CONSTRAINTS;
DROP TABLE categorias_carne CASCADE CONSTRAINTS;
DROP TABLE proveedores CASCADE CONSTRAINTS;
DROP TABLE supermercados CASCADE CONSTRAINTS;
/


/************************************************************************************
*
* 1. CREACIÓN DE TIPOS (VARRAY)
*
************************************************************************************/

CREATE OR REPLACE TYPE productos_alerta_varray AS VARRAY(50) OF NUMBER; -- Array para guardar IDs
/


/************************************************************************************
*
* 2. CREACIÓN DE TABLAS (Dominio: Carnicería)
*
************************************************************************************/

CREATE TABLE supermercados (
    supermercado_id     NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150)   NOT NULL,
    direccion           VARCHAR2(200),
    telefono            VARCHAR2(20),
    correo_contacto     VARCHAR2(100),
    estado              CHAR(1)         DEFAULT 'A' CHECK (estado IN ('A','I')),
    fecha_registro      DATE            DEFAULT SYSDATE
);

CREATE TABLE proveedores (
    proveedor_id        NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150)   NOT NULL,
    rut                 VARCHAR2(20)    UNIQUE NOT NULL,
    telefono            VARCHAR2(20),
    correo              VARCHAR2(100)   UNIQUE NOT NULL,
    estado              CHAR(1)         DEFAULT 'A' CHECK (estado IN ('A','I')),
    fecha_registro      DATE            DEFAULT SYSDATE,
    supermercado_id     NUMBER(10)      REFERENCES supermercados(supermercado_id)
);

CREATE TABLE categorias_carne (
    categoria_id        NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(100)   NOT NULL,
    descripcion         VARCHAR2(200),
    estado              CHAR(1)         DEFAULT 'A' CHECK (estado IN ('A','I')),
    supermercado_id     NUMBER(10)      REFERENCES supermercados(supermercado_id)
);

CREATE TABLE empleados (
    empleado_id         NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150)   NOT NULL,
    rut                 VARCHAR2(20)    UNIQUE NOT NULL,
    cargo               VARCHAR2(100),
    telefono            VARCHAR2(20),
    correo              VARCHAR2(100),
    supermercado_id     NUMBER(10)      REFERENCES supermercados(supermercado_id),
    estado              CHAR(1)         DEFAULT 'A' CHECK (estado IN ('A','I'))
);

CREATE TABLE productos_carne (
    producto_id         NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(150)   NOT NULL,
    categoria_id        NUMBER(10)      REFERENCES categorias_carne(categoria_id),
    precio_por_kg       NUMBER(10,2)    CHECK (precio_por_kg > 0),
    stock_actual_kg     NUMBER(10,3)    DEFAULT 0 CHECK (stock_actual_kg >= 0),
    stock_minimo_kg     NUMBER(10,3)    DEFAULT 10 CHECK (stock_minimo_kg >= 0),
    proveedor_id        NUMBER(10)      REFERENCES proveedores(proveedor_id),
    supermercado_id     NUMBER(10)      REFERENCES supermercados(supermercado_id),
    estado              CHAR(1)         DEFAULT 'A' CHECK (estado IN ('A','I'))
);

CREATE TABLE ordenes_compra (
    orden_id            NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    proveedor_id        NUMBER(10)      REFERENCES proveedores(proveedor_id),
    supermercado_id     NUMBER(10)      REFERENCES supermercados(supermercado_id),
    fecha_orden         DATE            DEFAULT SYSDATE,
    total               NUMBER(12,2),
    estado              VARCHAR2(20)    DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'RECIBIDA', 'CANCELADA'))
);

CREATE TABLE detalle_orden (
    detalle_id          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    orden_id            NUMBER(10)      REFERENCES ordenes_compra(orden_id),
    producto_id         NUMBER(10)      REFERENCES productos_carne(producto_id),
    cantidad_kg         NUMBER(10,3)    CHECK (cantidad_kg > 0),
    precio_por_kg       NUMBER(10,2)    CHECK (precio_por_kg >= 0)
);

CREATE TABLE movimientos_inventario (
    movimiento_id       NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    producto_id         NUMBER(10)      REFERENCES productos_carne(producto_id),
    tipo_movimiento     VARCHAR2(20)    CHECK (tipo_movimiento IN ('INGRESO','EGRESO', 'MERMA')),
    cantidad_kg         NUMBER(10,3)    CHECK (cantidad_kg > 0),
    fecha_movimiento    DATE            DEFAULT SYSDATE,
    observacion         VARCHAR2(200),
    empleado_id         NUMBER(10)      REFERENCES empleados(empleado_id),
    supermercado_id     NUMBER(10)      REFERENCES supermercados(supermercado_id)
);

CREATE TABLE alertas_inventario (
    alerta_id           NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    producto_id         NUMBER(10)      REFERENCES productos_carne(producto_id),
    fecha_alerta        DATE            DEFAULT SYSDATE,
    tipo_alerta         VARCHAR2(50)    CHECK (tipo_alerta IN ('BAJO STOCK','SIN STOCK', 'POR_VENCER')),
    descripcion         VARCHAR2(200)   NOT NULL,
    atendida            CHAR(1)         DEFAULT 'N' CHECK (atendida IN ('S','N'))
);

CREATE TABLE auditorias_inventario (
    auditoria_id        NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    producto_id         NUMBER(10)      REFERENCES productos_carne(producto_id),
    fecha_hora          TIMESTAMP       DEFAULT SYSTIMESTAMP,
    empleado_id         NUMBER(10)      REFERENCES empleados(empleado_id),
    supermercado_id     NUMBER(10)      REFERENCES supermercados(supermercado_id),
    stock_sistema_kg    NUMBER(10,3), -- El stock ANTES del ajuste
    stock_real_kg       NUMBER(10,3), -- El stock contado (NUEVO)
    diferencia_kg       NUMBER(10,3), -- real - sistema
    motivo              VARCHAR2(200)
);
/


/************************************************************************************
*
* 3. CREACIÓN DE TRIGGERS
*
************************************************************************************/

CREATE OR REPLACE TRIGGER trg_alerta_stock
AFTER UPDATE OF stock_actual_kg ON productos_carne
FOR EACH ROW
DECLARE
    v_tipo_alerta VARCHAR2(50);
BEGIN
    IF :NEW.stock_actual_kg <= NVL(:NEW.stock_minimo_kg, 0) AND (:OLD.stock_actual_kg > NVL(:NEW.stock_minimo_kg, 0) OR :OLD.stock_actual_kg IS NULL) THEN
        IF :NEW.stock_actual_kg = 0 THEN
            v_tipo_alerta := 'SIN STOCK';
        ELSE
            v_tipo_alerta := 'BAJO STOCK';
        END IF;

        DECLARE
            l_count NUMBER := 0;
        BEGIN
            SELECT COUNT(*) INTO l_count
            FROM alertas_inventario
            WHERE producto_id = :NEW.producto_id
              AND tipo_alerta = v_tipo_alerta
              AND atendida = 'N';

            IF l_count = 0 THEN
               INSERT INTO alertas_inventario (producto_id, tipo_alerta, descripcion)
               VALUES (:NEW.producto_id, v_tipo_alerta, 'El corte "' || :NEW.nombre || '" requiere reposición.');
            END IF;
        END;
    END IF;
END;
/


/************************************************************************************
*
* 4. PAQUETE CENTRALIZADO
*
************************************************************************************/

-- 4.1. Especificación del Paquete
CREATE OR REPLACE PACKAGE pkg_inventario_carnes AS

    PROCEDURE registrar_movimiento(
        p_producto_id       NUMBER,
        p_tipo_movimiento   VARCHAR2,
        p_cantidad_kg       NUMBER,
        p_empleado_id       NUMBER,
        p_supermercado_id   NUMBER
    );

    FUNCTION verificar_stock_kg(p_producto_id NUMBER) RETURN NUMBER;

    PROCEDURE crear_orden_compra_header(
        p_proveedor_id      NUMBER,
        p_supermercado_id   NUMBER,
        p_nueva_orden_id    OUT NUMBER
    );

    PROCEDURE agregar_detalle_orden(
        p_orden_id          NUMBER,
        p_producto_id       NUMBER,
        p_cantidad_kg       NUMBER,
        p_precio_por_kg     NUMBER
    );

    PROCEDURE recibir_orden_compra(
        p_orden_id      NUMBER,
        p_empleado_id   NUMBER
    );

    FUNCTION obtener_productos_bajo_minimo_categoria (
        p_categoria_id NUMBER
    ) RETURN productos_alerta_varray;

    PROCEDURE registrar_auditoria_conteo (
        p_producto_id     IN NUMBER,
        p_cantidad_real_kg IN NUMBER,
        p_empleado_id     IN NUMBER,
        p_supermercado_id IN NUMBER,
        p_motivo          IN VARCHAR2 DEFAULT 'CONTEO FISICO'
    );

END pkg_inventario_carnes;
/

-- 4.2. Cuerpo del Paquete
CREATE OR REPLACE PACKAGE BODY pkg_inventario_carnes AS

    e_stock_insuficiente EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_stock_insuficiente, -20010);

    PROCEDURE p_actualizar_stock(p_producto_id NUMBER, p_delta_kg NUMBER) IS
    BEGIN
        UPDATE productos_carne SET stock_actual_kg = NVL(stock_actual_kg,0) + p_delta_kg
        WHERE producto_id = p_producto_id;
    END p_actualizar_stock;

    PROCEDURE registrar_movimiento(
        p_producto_id       NUMBER,
        p_tipo_movimiento   VARCHAR2,
        p_cantidad_kg       NUMBER,
        p_empleado_id       NUMBER,
        p_supermercado_id   NUMBER
    ) IS
        v_stock_actual_kg NUMBER;
        v_sign NUMBER;
    BEGIN
        IF p_cantidad_kg <= 0 THEN
            RAISE_APPLICATION_ERROR(-20011, 'La cantidad en KG debe ser mayor a cero');
        END IF;

        SELECT NVL(stock_actual_kg,0) INTO v_stock_actual_kg FROM productos_carne WHERE producto_id = p_producto_id FOR UPDATE;

        IF p_tipo_movimiento = 'EGRESO' OR p_tipo_movimiento = 'MERMA' THEN
            IF v_stock_actual_kg < p_cantidad_kg THEN
                RAISE e_stock_insuficiente;
            END IF;
            v_sign := -1;
        ELSIF p_tipo_movimiento = 'INGRESO' THEN
            v_sign := 1;
        ELSE
            RAISE_APPLICATION_ERROR(-20012, 'Tipo de movimiento inválido. Usar INGRESO, EGRESO o MERMA');
        END IF;

        INSERT INTO movimientos_inventario (
            producto_id, tipo_movimiento, cantidad_kg, empleado_id, supermercado_id
        ) VALUES (
            p_producto_id, p_tipo_movimiento, p_cantidad_kg, p_empleado_id, p_supermercado_id
        );

        p_actualizar_stock(p_producto_id, v_sign * p_cantidad_kg);

    EXCEPTION
        WHEN e_stock_insuficiente THEN
            RAISE_APPLICATION_ERROR(-20010, 'Stock en KG insuficiente para el producto ' || p_producto_id);
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20013, 'Producto (corte) no encontrado: ' || p_producto_id);
    END registrar_movimiento;

    FUNCTION verificar_stock_kg(p_producto_id NUMBER) RETURN NUMBER IS
        v_stock_kg NUMBER;
    BEGIN
        SELECT NVL(stock_actual_kg,0) INTO v_stock_kg FROM productos_carne WHERE producto_id = p_producto_id;
        RETURN v_stock_kg;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END verificar_stock_kg;

    PROCEDURE crear_orden_compra_header(
        p_proveedor_id      NUMBER,
        p_supermercado_id   NUMBER,
        p_nueva_orden_id    OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO ordenes_compra (proveedor_id, supermercado_id, fecha_orden, total, estado)
        VALUES (p_proveedor_id, p_supermercado_id, SYSDATE, 0, 'PENDIENTE')
        RETURNING orden_id INTO p_nueva_orden_id;

    EXCEPTION
        WHEN OTHERS THEN
             RAISE_APPLICATION_ERROR(-20020, 'Error al crear la cabecera de la orden: ' || SQLERRM);
    END crear_orden_compra_header;

    PROCEDURE agregar_detalle_orden(
        p_orden_id          NUMBER,
        p_producto_id       NUMBER,
        p_cantidad_kg       NUMBER,
        p_precio_por_kg     NUMBER
    ) IS
        v_total_linea NUMBER;
    BEGIN
        INSERT INTO detalle_orden (orden_id, producto_id, cantidad_kg, precio_por_kg)
        VALUES (p_orden_id, p_producto_id, p_cantidad_kg, p_precio_por_kg);

        v_total_linea := p_cantidad_kg * p_precio_por_kg;

        UPDATE ordenes_compra
        SET total = NVL(total, 0) + v_total_linea
        WHERE orden_id = p_orden_id;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
             RAISE_APPLICATION_ERROR(-20021, 'Orden ID (' || p_orden_id || ') o Producto ID (' || p_producto_id || ') no existe.');
        WHEN OTHERS THEN
             RAISE_APPLICATION_ERROR(-20020, 'Error al agregar detalle a la orden: ' || SQLERRM);
    END agregar_detalle_orden;

    PROCEDURE recibir_orden_compra(
        p_orden_id      NUMBER,
        p_empleado_id   NUMBER
    ) IS
        CURSOR c_detalle IS
            SELECT producto_id, cantidad_kg FROM detalle_orden WHERE orden_id = p_orden_id;

        v_supermercado_id NUMBER;
        v_orden_estado    VARCHAR2(20);
    BEGIN
        SELECT estado, supermercado_id
        INTO v_orden_estado, v_supermercado_id
        FROM ordenes_compra
        WHERE orden_id = p_orden_id;

        IF v_orden_estado = 'RECIBIDA' THEN
            RAISE_APPLICATION_ERROR(-20024, 'Esta orden (' || p_orden_id || ') ya ha sido recibida anteriormente.');
        ELSIF v_orden_estado = 'CANCELADA' THEN
             RAISE_APPLICATION_ERROR(-20025, 'No se puede recibir una orden cancelada (' || p_orden_id || ').');
        END IF;

        FOR v_row IN c_detalle LOOP
            registrar_movimiento(
                p_producto_id       => v_row.producto_id,
                p_tipo_movimiento   => 'INGRESO',
                p_cantidad_kg       => v_row.cantidad_kg,
                p_empleado_id       => p_empleado_id,
                p_supermercado_id   => v_supermercado_id
            );
        END LOOP;

        UPDATE ordenes_compra SET estado = 'RECIBIDA' WHERE orden_id = p_orden_id;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20022, 'La orden de compra no existe: ' || p_orden_id);
         WHEN OTHERS THEN
             RAISE_APPLICATION_ERROR(-20023, 'Error al procesar la recepción de la orden ' || p_orden_id || ': ' || SQLERRM);
    END recibir_orden_compra;

    FUNCTION obtener_productos_bajo_minimo_categoria (
        p_categoria_id NUMBER
    ) RETURN productos_alerta_varray
    IS
        TYPE t_producto_simple_rec IS RECORD (
            id      productos_carne.producto_id%TYPE,
            nombre  productos_carne.nombre%TYPE,
            stock   productos_carne.stock_actual_kg%TYPE,
            minimo  productos_carne.stock_minimo_kg%TYPE
        );
        v_producto t_producto_simple_rec;

        CURSOR c_productos_categoria IS
            SELECT producto_id, nombre, stock_actual_kg, stock_minimo_kg
            FROM productos_carne
            WHERE categoria_id = p_categoria_id
              AND stock_actual_kg < stock_minimo_kg;

        -- Variable para construir el resultado VARRAY
        v_lista_ids productos_alerta_varray := productos_alerta_varray();
        v_contador PLS_INTEGER := 0;

    BEGIN
        OPEN c_productos_categoria;
        LOOP
            FETCH c_productos_categoria INTO v_producto;
            EXIT WHEN c_productos_categoria%NOTFOUND;

            v_contador := v_contador + 1;
            v_lista_ids.EXTEND;
            v_lista_ids(v_contador) := v_producto.id;

            DBMS_OUTPUT.PUT_LINE('Bajo mínimo: ' || v_producto.nombre || ' (Stock: '|| v_producto.stock ||')');

        END LOOP;
        CLOSE c_productos_categoria;

        RETURN v_lista_ids;

    EXCEPTION
        WHEN OTHERS THEN
            IF c_productos_categoria%ISOPEN THEN
                CLOSE c_productos_categoria;
            END IF;
            DBMS_OUTPUT.PUT_LINE('Error en obtener_productos_bajo_minimo: ' || SQLERRM);
            RETURN productos_alerta_varray();
    END obtener_productos_bajo_minimo_categoria;


    PROCEDURE registrar_auditoria_conteo (
        p_producto_id     IN NUMBER,
        p_cantidad_real_kg IN NUMBER,
        p_empleado_id     IN NUMBER,
        p_supermercado_id IN NUMBER,
        p_motivo          IN VARCHAR2 DEFAULT 'CONTEO FISICO'
    )
    IS
        v_stock_sistema_kg NUMBER;
        v_diferencia_kg    NUMBER;
        e_producto_invalido EXCEPTION;
        PRAGMA EXCEPTION_INIT(e_producto_invalido, -20005);
    BEGIN
        -- 1. Validar cantidad real (no puede ser negativa)
        IF p_cantidad_real_kg < 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'La cantidad real contada no puede ser negativa.');
        END IF;

        -- 2. Obtener el stock actual del sistema (y bloquear la fila)
        BEGIN
            SELECT stock_actual_kg
            INTO v_stock_sistema_kg
            FROM productos_carne
            WHERE producto_id = p_producto_id
            FOR UPDATE; -- Bloquea la fila para esta transacción
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20005, 'El producto ID ' || p_producto_id || ' no existe.');
        END;

        -- 3. Calcular la diferencia
        v_diferencia_kg := p_cantidad_real_kg - v_stock_sistema_kg;

        -- 4. Si hay una diferencia, registrarla y ajustar el stock
        IF v_diferencia_kg != 0 THEN
            DBMS_OUTPUT.PUT_LINE('Ajuste detectado. Diferencia: ' || v_diferencia_kg || ' kg.');

            -- 4a. Insertar en la tabla de auditoría de inventario
            INSERT INTO auditorias_inventario (
                producto_id,
                fecha_hora,
                empleado_id,
                supermercado_id,
                stock_sistema_kg,
                stock_real_kg,
                diferencia_kg,
                motivo
            )
            VALUES (
                p_producto_id,
                SYSTIMESTAMP,
                p_empleado_id,
                p_supermercado_id,
                v_stock_sistema_kg,     -- Lo que el sistema CREÍA que tenía
                p_cantidad_real_kg,   -- Lo que se CONTÓ realmente
                v_diferencia_kg,      -- La diferencia a ajustar
                p_motivo
            );

            -- 4b. Actualizar (corregir) el stock en la tabla principal
            UPDATE productos_carne
            SET stock_actual_kg = p_cantidad_real_kg
            WHERE producto_id = p_producto_id;

        ELSE
            -- 4c. Si no hay diferencia, solo informarlo (opcional)
             DBMS_OUTPUT.PUT_LINE('Conteo verificado para producto ' || p_producto_id || '. Stock del sistema coincide.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error en auditoria de conteo: ' || SQLERRM);
            ROLLBACK; -- Deshace cualquier cambio si algo falla
            RAISE;    -- Vuelve a lanzar el error
    END registrar_auditoria_conteo;


END pkg_inventario_carnes;
/

SET SERVEROUTPUT ON;
COMMIT;

/************************************************************************************
*
* SECCIÓN DE PRUEBAS
*
************************************************************************************/


/************************************************************************************
*
* 1. INSERCIÓN DE DATOS DE PRUEBA (40 INSERCIONES)
* (Bloque INSERT corregido)
*
************************************************************************************/
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- 1. Creando 40 registros iniciales... ---');

    -- Insertar 3 Supermercados
    INSERT INTO supermercados (nombre, direccion) VALUES ('Supermercado Central', 'Av. Principal 123'); -- ID 1
    INSERT INTO supermercados (nombre, direccion) VALUES ('Sucursal Norte', 'Calle Falsa 456'); -- ID 2
    INSERT INTO supermercados (nombre, direccion, estado) VALUES ('Bodega Logística', 'Ruta 5 Sur Km 100', 'I'); -- ID 3

    -- Insertar 8 Empleados
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id) VALUES ('Juan Pérez', '1-1', 'Jefe de Carnicería', 1); -- ID 1
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id) VALUES ('Ana Rojas', '2-2', 'Carnicera', 1); -- ID 2
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id) VALUES ('Carlos Muñoz', '3-3', 'Bodeguero', 3); -- ID 3
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id) VALUES ('María López', '4-4', 'Carnicera', 2); -- ID 4
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id) VALUES ('Pedro Soto', '5-5', 'Jefe de Sección', 2); -- ID 5
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id) VALUES ('Luisa Vera', '6-6', 'Ayudante Carnicero', 1); -- ID 6
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id) VALUES ('Jorge Díaz', '7-7', 'Reponedor', 2); -- ID 7
    INSERT INTO empleados (nombre, rut, cargo, supermercado_id, estado) VALUES ('Elena Gómez', '8-8', 'Ex-Carnicera', 1, 'I'); -- ID 8

    -- Insertar 5 Proveedores
    INSERT INTO proveedores (nombre, rut, correo, supermercado_id) VALUES ('Frigorífico del Sur', '77.123.456-K', 'ventas@frigosur.cl', 1); -- ID 1
    INSERT INTO proveedores (nombre, rut, correo, supermercado_id) VALUES ('Carnes Premium Ltda.', '78.987.654-J', 'contacto@carnespremium.cl', 1); -- ID 2
    INSERT INTO proveedores (nombre, rut, correo, supermercado_id) VALUES ('Distribuidora Andina', '76.543.210-9', 'pedidos@andina.com', 2); -- ID 3
    INSERT INTO proveedores (nombre, rut, correo, supermercado_id) VALUES ('Aves del Campo', '75.111.222-3', 'aves@campo.cl', 1); -- ID 4
    INSERT INTO proveedores (nombre, rut, correo, supermercado_id, estado) VALUES ('Proveedor Antiguo', '70.000.000-0', 'old@prov.com', 1, 'I'); -- ID 5

    -- Insertar 5 Categorías
    INSERT INTO categorias_carne (nombre, supermercado_id) VALUES ('Vacuno', 1); -- ID 1
    INSERT INTO categorias_carne (nombre, supermercado_id) VALUES ('Pollo', 1); -- ID 2
    INSERT INTO categorias_carne (nombre, supermercado_id) VALUES ('Cerdo', 1); -- ID 3
    INSERT INTO categorias_carne (nombre, supermercado_id) VALUES ('Pavo', 2); -- ID 4
    INSERT INTO categorias_carne (nombre, supermercado_id) VALUES ('Cordero', 1); -- ID 5

    -- Insertar 19 Productos
    -- Vacuno (Cat 1)
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Lomo Vetado', 1, 19990, 5.0, 1, 1); -- ID 1
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Asiento Picana', 1, 15500, 8.0, 2, 1); -- ID 2
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Entraña', 1, 22500, 3.0, 1, 1); -- ID 3
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Posta Negra', 1, 11990, 10.0, 2, 2); -- ID 4
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Tapabarriga', 1, 13490, 6.0, 1, 1); -- ID 5
    -- Pollo (Cat 2)
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Pechuga Entera', 2, 6990, 10.0, 4, 1); -- ID 6
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_actual_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Trutro Corto', 2, 4500, 5.0, 15.0, 4, 1); -- ID 7
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Alitas de Pollo', 2, 3990, 12.0, 4, 2); -- ID 8
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Pollo Entero Faenado', 2, 3500, 8.0, 4, 1); -- ID 9
    -- Cerdo (Cat 3)
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Pulpa Pierna', 3, 7200, 7.5, 2, 1); -- ID 10
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Costillar Ahumado', 3, 9900, 4.0, 2, 1); -- ID 11
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Lomo Centro', 3, 8500, 5.0, 3, 2); -- ID 12
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Chuleta Parrillera', 3, 7990, 6.0, 3, 1); -- ID 13
    -- Pavo (Cat 4)
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Pechuga de Pavo Deshuesada', 4, 8990, 5.0, 4, 2); -- ID 14
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Pavo Entero Congelado', 4, 5500, 3.0, 4, 2); -- ID 15
    -- Cordero (Cat 5)
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Pierna de Cordero', 5, 14990, 2.0, 1, 1); -- ID 16
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id)
    VALUES ('Chuletas de Cordero', 5, 18990, 2.5, 2, 1); -- ID 17
    -- Producto Inactivo
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, proveedor_id, supermercado_id, estado)
    VALUES ('Corte Descontinuado', 1, 5000, 1.0, 1, 1, 'I'); -- ID 18
    -- Producto sin proveedor asignado
    INSERT INTO productos_carne (nombre, categoria_id, precio_por_kg, stock_minimo_kg, supermercado_id)
    VALUES ('Carne Molida Especial', 1, 9500, 10.0, 1); -- ID 19

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('40 registros iniciales creados.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al insertar los 40 datos: ' || SQLERRM);
        ROLLBACK;
END;
/


/************************************************************************************
*
* 2. PRUEBAS EXITOSAS ADICIONALES
*
************************************************************************************/
DECLARE
    v_stock_pechuga NUMBER;
BEGIN
    -- 2.1 Prueba Exitosa: Verificar stock inicial CERO
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 2.1 Prueba Exitosa: Verificar stock inicial CERO ---');
    v_stock_pechuga := pkg_inventario_carnes.verificar_stock_kg(6);
    DBMS_OUTPUT.PUT_LINE('Stock inicial de Pechuga Entera (ID 6): ' || v_stock_pechuga || ' kg (Esperado: 0)');

    -- 2.2 Prueba Exitosa: Ingreso inicial de varios productos (Usando EXECUTE)
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 2.2 Prueba Exitosa: Ingreso inicial de varios productos ---');
    EXECUTE IMMEDIATE 'BEGIN pkg_inventario_carnes.registrar_movimiento(1, ''INGRESO'', 20.5, 1, 1); END;';
    EXECUTE IMMEDIATE 'BEGIN pkg_inventario_carnes.registrar_movimiento(6, ''INGRESO'', 35.0, 1, 1); END;';
    EXECUTE IMMEDIATE 'BEGIN pkg_inventario_carnes.registrar_movimiento(10, ''INGRESO'', 15.8, 1, 1); END;';
    DBMS_OUTPUT.PUT_LINE('Ingresos registrados para Lomo(1), Pechuga(6) y Pulpa(10).');
    COMMIT;

    -- 2.3 Prueba Exitosa: Registrar MERMA (Usando EXECUTE)
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 2.3 Prueba Exitosa: Registrar MERMA ---');
    EXECUTE IMMEDIATE 'BEGIN pkg_inventario_carnes.registrar_movimiento(10, ''MERMA'', 0.3, 2, 1); END;';
    DBMS_OUTPUT.PUT_LINE('MERMA de 0.3 kg de Pulpa Pierna (ID 10) registrada.');
    COMMIT;

    -- 2.4 Prueba Exitosa: Egreso que deja Lomo bajo mínimo (Usando EXECUTE)
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 2.4 Prueba Exitosa: Egreso que deja Lomo bajo mínimo (para prueba 5) ---');
    EXECUTE IMMEDIATE 'BEGIN pkg_inventario_carnes.registrar_movimiento(1, ''EGRESO'', 16.0, 2, 1); END;';
    DBMS_OUTPUT.PUT_LINE('EGRESO de 16.0 kg de Lomo Vetado REGISTRADO.');
    DBMS_OUTPUT.PUT_LINE('El stock de Lomo (ID 1) está ahora en 4.5 kg.');
    COMMIT;
END;
/


/************************************************************************************
*
* 3. PRUEBAS FALLIDAS ADICIONALES (CONTROLADAS)
*
************************************************************************************/
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 3.1 Prueba Fallida: Registrar movimiento con cantidad negativa ---');
    BEGIN
        pkg_inventario_carnes.registrar_movimiento(p_producto_id => 1, p_tipo_movimiento => 'INGRESO', p_cantidad_kg => -5.0, p_empleado_id => 1, p_supermercado_id => 1);
        DBMS_OUTPUT.PUT_LINE('ERROR: Se permitió registrar cantidad negativa!');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ÉXITO (Fallo esperado): ' || SQLERRM);
            ROLLBACK;
    END;

    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 3.2 Prueba Fallida: Agregar detalle a orden inexistente ---');
    BEGIN
        pkg_inventario_carnes.agregar_detalle_orden(p_orden_id => 999, p_producto_id => 1, p_cantidad_kg => 1.0, p_precio_por_kg => 19000);
        DBMS_OUTPUT.PUT_LINE('ERROR: Se permitió agregar detalle a orden 999!');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ÉXITO (Fallo esperado): ' || SQLERRM);
            ROLLBACK;
    END;

     DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 3.3 Prueba Fallida: Registrar MERMA con stock insuficiente ---');
    BEGIN
        -- Quedan 4.5 kg de Lomo (ID 1), intentamos mermar 5kg
        pkg_inventario_carnes.registrar_movimiento(p_producto_id => 1, p_tipo_movimiento => 'MERMA', p_cantidad_kg => 5.0, p_empleado_id => 2, p_supermercado_id => 1);
        DBMS_OUTPUT.PUT_LINE('ERROR: Se permitió MERMA con stock insuficiente!');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ÉXITO (Fallo esperado): ' || SQLERRM);
            ROLLBACK;
    END;

END;
/


/************************************************************************************
*
* 4. PRUEBA DEL PROCESO DE COMPRA
*
************************************************************************************/
DECLARE
    v_nueva_orden_id NUMBER;
    v_stock_pollo_antes NUMBER;
    v_stock_pollo_despues NUMBER;
    v_orden_estado VARCHAR2(20);
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 4.1 Probando proceso de compra (Paso 1: Crear Orden)... ---');
    pkg_inventario_carnes.crear_orden_compra_header(p_proveedor_id => 1, p_supermercado_id => 1, p_nueva_orden_id => v_nueva_orden_id);
    DBMS_OUTPUT.PUT_LINE('Orden de compra creada con ID: ' || v_nueva_orden_id);

    DBMS_OUTPUT.PUT_LINE('--- 4.2 Agregando productos a la orden... ---');
    pkg_inventario_carnes.agregar_detalle_orden(p_orden_id => v_nueva_orden_id, p_producto_id => 6, p_cantidad_kg => 30.0, p_precio_por_kg => 6500);
    pkg_inventario_carnes.agregar_detalle_orden(p_orden_id => v_nueva_orden_id, p_producto_id => 7, p_cantidad_kg => 25.0, p_precio_por_kg => 4000);
    DBMS_OUTPUT.PUT_LINE('Productos agregados a la orden.');

    SELECT estado INTO v_orden_estado FROM ordenes_compra WHERE orden_id = v_nueva_orden_id;
    DBMS_OUTPUT.PUT_LINE('Estado actual de la orden: ' || v_orden_estado);
    v_stock_pollo_antes := pkg_inventario_carnes.verificar_stock_kg(6);
    DBMS_OUTPUT.PUT_LINE('Stock de Pechuga (ID 6) ANTES de recibir: ' || v_stock_pollo_antes || ' kg');

    DBMS_OUTPUT.PUT_LINE('--- 4.3 Recibiendo el pedido del proveedor... ---');
    pkg_inventario_carnes.recibir_orden_compra(p_orden_id => v_nueva_orden_id, p_empleado_id => 1);
    DBMS_OUTPUT.PUT_LINE('¡Orden RECIBIDA! El stock ha sido actualizado.');
    v_stock_pollo_despues := pkg_inventario_carnes.verificar_stock_kg(6);
    DBMS_OUTPUT.PUT_LINE('Stock de Pechuga (ID 6) DESPUÉS de recibir: ' || v_stock_pollo_despues || ' kg');

    SELECT estado INTO v_orden_estado FROM ordenes_compra WHERE orden_id = v_nueva_orden_id;
    DBMS_OUTPUT.PUT_LINE('Estado final de la orden: ' || v_orden_estado);
    COMMIT;

    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 4.4 Prueba Fallida: Intentar recibir la MISMA orden de nuevo ---');
    BEGIN
        pkg_inventario_carnes.recibir_orden_compra(p_orden_id => v_nueva_orden_id, p_empleado_id => 1);
        DBMS_OUTPUT.PUT_LINE('ERROR: Se permitió recibir una orden ya recibida!');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ÉXITO (Fallo esperado): ' || SQLERRM);
            ROLLBACK;
    END;
END;
/

/************************************************************************************
*
* 5. PRUEBA (VARRAY/RECORD)
*
************************************************************************************/
DECLARE
    v_lista_ids_vacuno productos_alerta_varray;
    v_lista_ids_pollo  productos_alerta_varray;
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 5.1 Probando obtener_productos_bajo_minimo_categoria (Vacuno)... ---');
    -- Lomo (ID 1) debería estar bajo mínimo (4.5kg < 5kg)
    v_lista_ids_vacuno := pkg_inventario_carnes.obtener_productos_bajo_minimo_categoria(p_categoria_id => 1);

    IF v_lista_ids_vacuno IS NOT NULL AND v_lista_ids_vacuno.COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('Productos Vacuno bajo mínimo encontrados (' || v_lista_ids_vacuno.COUNT || '):');
        FOR i IN 1..v_lista_ids_vacuno.COUNT LOOP
            DBMS_OUTPUT.PUT_LINE('- ID Producto: ' || v_lista_ids_vacuno(i));
        END LOOP;
    ELSE
        DBMS_OUTPUT.PUT_LINE('No se encontraron productos Vacuno bajo mínimo.');
    END IF;

    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 5.2 Probando obtener_productos_bajo_minimo_categoria (Pollo)... ---');
    -- Trutro Corto (ID 7) debería estar bajo mínimo (5kg < 15kg)
    v_lista_ids_pollo := pkg_inventario_carnes.obtener_productos_bajo_minimo_categoria(p_categoria_id => 2);

    IF v_lista_ids_pollo IS NOT NULL AND v_lista_ids_pollo.COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('Productos Pollo bajo mínimo encontrados (' || v_lista_ids_pollo.COUNT || '):');
        FOR i IN 1..v_lista_ids_pollo.COUNT LOOP
            DBMS_OUTPUT.PUT_LINE('- ID Producto: ' || v_lista_ids_pollo(i));
        END LOOP;
    ELSE
        DBMS_OUTPUT.PUT_LINE('No se encontraron productos Pollo bajo mínimo.');
    END IF;

     DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- Fin de la prueba 5 ---');
END;
/


/************************************************************************************
*
* 6. PRUEBA DE AUDITORIA(registrar_auditoria_conteo)
*
************************************************************************************/
DECLARE
    v_producto_id_test    NUMBER := 6; -- Pechuga Entera (ID 6)
    v_stock_sistema_antes NUMBER;
    v_stock_sistema_despues NUMBER;
    v_conteo_real_kg      NUMBER := 60.0; 
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- 6.1 Probando función de Auditoría de Conteo Físico ---');

    -- 1. Verificar el stock del sistema ANTES del ajuste
    --    (Debería ser 65.0 kg si la prueba 4.3 se ejecutó)
    v_stock_sistema_antes := pkg_inventario_carnes.verificar_stock_kg(v_producto_id_test);
    DBMS_OUTPUT.PUT_LINE('Stock en Sistema (Antes): ' || v_stock_sistema_antes || ' kg para Producto ID ' || v_producto_id_test);

    -- 2. Simular el conteo
    DBMS_OUTPUT.PUT_LINE('Realizando conteo... Se contaron físicamente ' || v_conteo_real_kg || ' kg.');
    DBMS_OUTPUT.PUT_LINE('Se espera un ajuste/diferencia de: ' || (v_conteo_real_kg - v_stock_sistema_antes) || ' kg.');

    -- 3. Ejecutar el procedimiento de auditoría
    pkg_inventario_carnes.registrar_auditoria_conteo(
        p_producto_id     => v_producto_id_test,
        p_cantidad_real_kg => v_conteo_real_kg,
        p_empleado_id     => 5,  -- Pedro Soto (Jefe de Sección)
        p_supermercado_id => 1,
        p_motivo          => 'AJUSTE POR CONTEO SEMANAL'
    );

    -- 4. Verificar el stock del sistema DESPUÉS del ajuste
    v_stock_sistema_despues := pkg_inventario_carnes.verificar_stock_kg(v_producto_id_test);
    DBMS_OUTPUT.PUT_LINE('Stock en Sistema (Después): ' || v_stock_sistema_despues || ' kg.');

    IF v_stock_sistema_despues = v_conteo_real_kg THEN
        DBMS_OUTPUT.PUT_LINE('ÉXITO: El stock del sistema se ha corregido al conteo real (' || v_conteo_real_kg || ' kg).');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FALLO: El stock del sistema (' || v_stock_sistema_despues || ') NO se corrigió a (' || v_conteo_real_kg || ').');
    END IF;

    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- PRUEBAS FINALIZADAS ---');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Prueba 6.1 fallida: ' || SQLERRM);
        ROLLBACK;
END;
/

SELECT * FROM auditorias_inventario WHERE producto_id = 6 ORDER BY fecha_hora DESC;
SELECT producto_id, nombre, stock_actual_kg FROM productos_carne WHERE producto_id = 6;
SELECT * FROM auditorias_inventario; 



